### ISSUE TITLE
[feat] course 테이블 출발지, 목적지에도 위도, 경도 컬럼 추가하기

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamChaRo/ChaRo-Server#13]
## 💙 제목
* course 테이블 출발지, 목적지에도 위도, 경도 컬럼 추가하기

## 🚙 작업 브랜치
#feat/12

## 📝 todo
- [x] course 테이블 sourceLatitude
- [x] course 테이블 sourceLongtitude
- [x] course 테이블 destinationLongtitude
- [x] course 테이블 destinationLatitude
