### ISSUE TITLE
[feat] 이미지 폴더링 고안

### ISSUE THREAD

**Issue by yaeoni** [TeamChaRo/ChaRo-Server#18]
## 💙 S3 이미지 폴더링
* 유저별 ( 프로필 이미지 및 디폴트 이미지 )
* 게시글별 ( 게시글 당 6개의 이미지 )
* 관리자 ( local, custom 속 이미지 )

## 🚙 작업 브랜치
feat/3

## 📝 todo
- [x] 폴더링 구조 공부 및 확정
- [x] 이미지 업로드 함수 수정(게시글, 프로필 이미지용)
- [ ] 비즈니스 로직 분리

**Comment by yaeoni** [comment]
[작성하기용, 이미지 여러개]
사실 s3는 폴더구조로 되어있지 않지만 simulating 해주는 것
따라서 나도 큰 구분은 두지 않고!

게시물 -> /post/:userid/Date.now().extname
유저별 프로필 이미지 -> /user/:userid.extname
관리자 -> public/ ~~~
