### ISSUE TITLE
[feat] 메인뷰 조회 API 기능

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamChaRo/ChaRo-Server#19]
## 💙 제목
* 메인뷰 조회 API 
## 🚙 작업 브랜치
#feat/19

## 📝 todo
- [x] 메인뷰 데이터 넣기
- [x] local 데이터 조회
- [x] customTheme 데이터 조회
- [x] trend 데이터 조회
- [x] banner 데이터 조회
- [x] todayCharo 데이터 조회
- [x] 데이터들 인기순으로 4개 파싱
- [x] 메인뷰 데이터 조회 최종 확인
- [ ] 메인뷰 추천 알고리즘 구현
- [x] res body 맞추기
