### ISSUE TITLE
[feat] DB 모델 구축 및 마이그레이션

### ISSUE THREAD

**Issue by yaeoni** [TeamChaRo/ChaRo-Server#2]
## 💙 DB 모델 마이그레이션
* 작성된 모델들을 DB에 테이블로 업로드합니다.

## 🚙 작업 브랜치
feat/2
## 📝 todo
- [x] migration 테스트
- [x] post model
- [x] post-image / post-course 
- [x] post-warning / post-theme
- [x] user 전달 받고 follow
- [x] saved / liked post
