### ISSUE TITLE
[fix] API 작성 중 생긴 DB 관련 구조 재정의

### ISSUE THREAD

**Issue by yaeoni** [TeamChaRo/ChaRo-Server#28]
## 💙 제목
* 각종 API 작성 중 생긴 models, DTO 등의 변경
## 🚙 작업 브랜치
feat/20
## 📝 todo
- [x] custom table : custom -> customTheme 로 수정
- [x] post table column명 변경
- [x] course table 경유지 null 허용토록 수정
- [x] warning, theme 테이블 삭제
- [x] post_has_warning, post_has_theme 테이블 구조 변경
- [x] 모든 모델들 중 post를 참조할 때 id 로 참조 -> postId로 참조토록 수정
