### ISSUE TITLE
[feat] 더보기 내 필터 기능 개발

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamChaRo/ChaRo-Server#48]
## 💙 더보기 필터
* 더보기 내에 인기순/최신순 필터 기능 개발
* 인기순 -> 기존 더보기 API 활용(URL 변경 필요, preview -> likePreview/:id/:identifier)
* 최신순 -> newPreview/:id/:identifier

## 🚙 작업 브랜치
feat/48

## 📝 todo
- [x] API 문서 컨펌
- [x] 최신순 필터 기능 개발
- [x] 인기순 필터 URL 변경
- [x] 테스트

**Comment by hwangJi-dev** [comment]
`예원씨. 앞으로 이슈번호와 브랜치번호 통일 부탁드릴게요^~^ `
