### ISSUE TITLE
[feat] 작성하기 시 주소(키워드) 검색 기록 저장/조회 API 구현

### ISSUE THREAD

**Issue by yaeoni** [TeamChaRo/ChaRo-Server#50]
## 💙 주소(키워드) 검색 기능
* 작성하기 때 지도에서 주소를 검색할 때 해당 키워드를 저장 및 조회하는 API 개발

## 🚙 작업 브랜치
feat/50
## 📝 todo
- [x] API 문서 컨펌
- [x] 테이블 모델 변경
- [x] 키워드 저장 API
- [x] 키워드 조회 API
- [x] 테스트
