### ISSUE TITLE
[feat] 검색하기 결과 조회 및 필터 구현 ⚙️

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamChaRo/ChaRo-Server#57]
## 💙 제목
**검색하기 결과 조회 및 필터 구현**

## 🚙 작업 브랜치
#feat/57

## 📝 todo
- [x] 검색하기 결과 조회
- [x] 검색하기 결과 좋아요순 조회
- [x]  검색하기 결과 최신순 조회
