### ISSUE TITLE
[feat] 인터페이스 DTO 분리 & 테이블 추가 및 조정

### ISSUE THREAD

**Issue by yaeoni** [TeamChaRo/ChaRo-Server#8]
## 💙 기능 설명
* 클라이언트 개발과 맞추기 위한 DTO 설계(게시물 상세 조회, 더보기 뷰, 마이페이지)

## 📝 todo
- [x] 최근 검색 테이블 추가
- [x] 경유지 테이블 조정
- [x] 메인뷰 DTO
- [x] 게시물 상세 조회 DTO
- [x] 최근 검색 기록 DTO
- [x] 더보기 버튼 클릭 시 조회 DTO
