### ISSUE TITLE
[docs] README.md 수정 (개발 사항 반영)

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamChaRo/ChaRo-Server#87]
## 💙 제목
* README.md 수정 (개발 사항 반영)

## 🚙 작업 브랜치
# docs/1

## 📝 todo
- [ ] README.md 수정
- [ ] 개발 담당자 쓰기
- [ ] 배너 사진 수정
- [ ] DTO 설명
